from openai import OpenAI
client = OpenAI(api_key="myapikey")

completion = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a text analyzer who specializes in scrutinizing job descriptions and seeing if the answers somebody gives to potential interview questions align with the job's values. You will be given a job description, interview question, and someone giving a sample response. Your job is to evaluate how well the response answers the question and aligns with the job description. Always give constructive criticsm to the user."},
        {
            "role": "user",
            "content": "Job Description: We're not rockstars or ninjas, just regular coders trying to make it a little easier to manage a doctor's office. Working in Ruby/Rails API with AngularJS/React front-end deployed on AWS cloud infrastructure we help keep track of patient appointments, drug inventory, and integrate with systems to send appointment reminders and bill insurance claims. We hire people we can trust. As soon as you hit merge, your code is headed to production (and ringing a gong in our Austin office) and you're given a wide berth to solve problems and improve our engineering team. Come join a 20-person engineering organization spread across three smaller feature teams where you can make a direct impact. Our Stack React/ES6 Front-end - Ruby on Rails API - MySQL - AWS - Docker What You'll Do Write and deploy code - Create tests - Work with product on stories - Improve our processes - Attend daily stand-ups - Stay curious and enjoy learning new things Desired Skills/Experience 4+ years Ruby, Python, Java, Javascript or other language - Strong problem-solving skills - Must be authorized to work in the United States About WeInfuse Come join our growing company. We are an established healthcare SaaS start-up with offices in Dallas and Austin. Founded in 2016, WeInfuse is an infusion center software and consulting organization. Our founders and their team have developed the first and only end-to-end software solution for infusion centers that has gained significant traction in the market. In addition to providing the industry’s leading SaaS solution, WeInfuse provides infusion center start-up, optimization and pharmaceutical manufacturer consulting services. Interview Question: What skills do you have that will be relevant to this position? User Response:  my 5+ years of experience as a software engineer, I have worked extensively with Ruby on Rails, JavaScript, and React, which aligns well with the stack at WeInfuse. I've successfully built and deployed APIs and full-stack applications that emphasize both usability and performance. My problem-solving skills are solid, which has helped me troubleshoot and improve processes on the go, an ability I developed while working on several SaaS projects in healthcare and finance. Additionally, I’m comfortable working in an agile environment, collaborating across teams, and have a strong track record of deploying code to production while ensuring high code quality through test-driven development. I believe this background, coupled with my curiosity and eagerness to learn, would allow me to make a valuable contribution to your team from day one."
        }
    ]
)
print(completion.choices[0].message)